# adjust to your env config
env:
  output_dir: "/mnt/ramdisksocialmedia/"
  chromedriver: "/usr/bin/chromedriver" 
  headless: true

# sudo mount -t tmpfs -o size=250G tmpfs /mnt/ramdisksocialmedia 
# sudo umount /mnt/ramdisksocialmedia 

